[[OpenFHE_int128]]
arch = "aarch64"
git-tree-sha1 = "a158e4ea2d88df37d4657b5e98c820ada2d8c7c8"
os = "macos"

    [[OpenFHE_int128.download]]
    sha256 = "3dccdfcf7b1dd7281f1792ed7211e5a8aead1cfeb18c831a97e2da2586c0a36e"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.4.2+0/OpenFHE_int128.v1.4.2.aarch64-apple-darwin.tar.gz"
[[OpenFHE_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61af4692b97d02403b369f3d6a2abd7665ee5a66"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "d5a80dfbe099c4044582206f8ecf3c6c3e37fb1c3fa81cb11b6f43d60617c9a6"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.4.2+0/OpenFHE_int128.v1.4.2.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenFHE_int128]]
arch = "aarch64"
git-tree-sha1 = "75f6266b20645ac4b598c7ef4faead75e833c668"
os = "freebsd"

    [[OpenFHE_int128.download]]
    sha256 = "852a49f156c20506387a705d0d08a94b38fefa176f06edfe0fb46680514e34f8"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.4.2+0/OpenFHE_int128.v1.4.2.aarch64-unknown-freebsd.tar.gz"
[[OpenFHE_int128]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7276162142f70fa3fa6cbb15792f14887196be01"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "fe6b426be0b85c33568730d82534ad8da8262da274619b8de84e04c13f05f7f2"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.4.2+0/OpenFHE_int128.v1.4.2.riscv64-linux-gnu-cxx11.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
git-tree-sha1 = "174d741cb0f46c8d3d73e9357d909df0b7525e63"
os = "macos"

    [[OpenFHE_int128.download]]
    sha256 = "1cbf585f2f72428fae2707f1448a4beeb662111bebc527c455c7e1fe40b57d83"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.4.2+0/OpenFHE_int128.v1.4.2.x86_64-apple-darwin.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51c2b33fd50f43395bc908def1c7753b4b8da8fd"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "5a98d7b087447f681b1dec2f4811cfb384cfcb948808d3ebe47b9566326e283c"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.4.2+0/OpenFHE_int128.v1.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
git-tree-sha1 = "3003a7ec8fcde4fb2c7add2d3b742a82f971859f"
os = "freebsd"

    [[OpenFHE_int128.download]]
    sha256 = "2f5afe7307d9e8653e537ef50cb20f3b8cdf4266952971ee6da81e2e091e2603"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.4.2+0/OpenFHE_int128.v1.4.2.x86_64-unknown-freebsd.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea52c83b0b1a48c5b76a17b97efab46abb82030a"
os = "windows"

    [[OpenFHE_int128.download]]
    sha256 = "992fab63fc874334951b48970673a7dcbf07a283134c4f50d1ec4c307f2befaf"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.4.2+0/OpenFHE_int128.v1.4.2.x86_64-w64-mingw32-cxx11.tar.gz"
