[[OpenFHE_int128]]
arch = "aarch64"
git-tree-sha1 = "94982c4a430eb6e158ba3a0e69b89a7cf36ed3dc"
julia_version = "1.10.0"
os = "macos"

    [[OpenFHE_int128.download]]
    sha256 = "a820dd018610070a892e0e2cb8b424f071901eddf03bf675f2bbcc7cfb952fc2"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[OpenFHE_int128]]
arch = "aarch64"
git-tree-sha1 = "94982c4a430eb6e158ba3a0e69b89a7cf36ed3dc"
julia_version = "1.11.1"
os = "macos"

    [[OpenFHE_int128.download]]
    sha256 = "a820dd018610070a892e0e2cb8b424f071901eddf03bf675f2bbcc7cfb952fc2"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[OpenFHE_int128]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c779e617b69e50375973ab89a2293aa7e96420ca"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "6ffce8d1cc94ddc4dcbb6e89cb84ad4990eecc179058d08fced5f4b159fdb930"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[OpenFHE_int128]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c779e617b69e50375973ab89a2293aa7e96420ca"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "6ffce8d1cc94ddc4dcbb6e89cb84ad4990eecc179058d08fced5f4b159fdb930"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.aarch64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[OpenFHE_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fcd5029503cba2d167267dce0a3811e3eecaceda"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "265e25f0ba36697841e45b06dd65364998ee3b2297e98e54d67da597765b0553"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[OpenFHE_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fcd5029503cba2d167267dce0a3811e3eecaceda"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "265e25f0ba36697841e45b06dd65364998ee3b2297e98e54d67da597765b0553"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
git-tree-sha1 = "dc17ef03b771f3797c525173dbea27b37665ff2b"
julia_version = "1.10.0"
os = "macos"

    [[OpenFHE_int128.download]]
    sha256 = "f154e60584c1ac6f471f0425cdc3f8ecd5dc6f9da3689c97673c6aedc7b15c29"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
git-tree-sha1 = "dc17ef03b771f3797c525173dbea27b37665ff2b"
julia_version = "1.11.1"
os = "macos"

    [[OpenFHE_int128.download]]
    sha256 = "f154e60584c1ac6f471f0425cdc3f8ecd5dc6f9da3689c97673c6aedc7b15c29"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31f002b81ee656419e153d3dc98c3acae2b91157"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "1f678ff2dc5dd3b0fb3def4b0936256dd6b7260195a1065b9afcfc78af7de4a3"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31f002b81ee656419e153d3dc98c3acae2b91157"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "1f678ff2dc5dd3b0fb3def4b0936256dd6b7260195a1065b9afcfc78af7de4a3"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.x86_64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2466ccb847662a5c0ea50afcb5843869ecb0b8e5"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "3a9e4ac74c4cf979cc58b2393f6de2ac8dcf18eb77009524f9e5e67e9774b326"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2466ccb847662a5c0ea50afcb5843869ecb0b8e5"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "3a9e4ac74c4cf979cc58b2393f6de2ac8dcf18eb77009524f9e5e67e9774b326"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
git-tree-sha1 = "d3fd182feb088126720b8e6b55a9e0f14c1504d4"
julia_version = "1.10.0"
os = "freebsd"

    [[OpenFHE_int128.download]]
    sha256 = "087bcdbaf08ba5f66ae6cf7c019c444023f6d9c8391907fb38713454b400727e"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
git-tree-sha1 = "d3fd182feb088126720b8e6b55a9e0f14c1504d4"
julia_version = "1.11.1"
os = "freebsd"

    [[OpenFHE_int128.download]]
    sha256 = "087bcdbaf08ba5f66ae6cf7c019c444023f6d9c8391907fb38713454b400727e"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.x86_64-unknown-freebsd-julia_version+1.11.1.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4c1769fc8005a7683bfab3a71529f20f7924657"
julia_version = "1.10.0"
os = "windows"

    [[OpenFHE_int128.download]]
    sha256 = "d4092c2aa2ccd8c9c17b464ba96e78c2eee0bdda764613c4d8f728d71d0a6c4a"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.x86_64-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4c1769fc8005a7683bfab3a71529f20f7924657"
julia_version = "1.11.1"
os = "windows"

    [[OpenFHE_int128.download]]
    sha256 = "d4092c2aa2ccd8c9c17b464ba96e78c2eee0bdda764613c4d8f728d71d0a6c4a"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.x86_64-w64-mingw32-cxx03-julia_version+1.11.1.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91d40a04e21cbc34c28b6670b60a5b66ecad6c0e"
julia_version = "1.10.0"
os = "windows"

    [[OpenFHE_int128.download]]
    sha256 = "cc9583fefa8f8efe525ab2657a106e3ab92f9669aa3c02feb4f062d2dbd131ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91d40a04e21cbc34c28b6670b60a5b66ecad6c0e"
julia_version = "1.11.1"
os = "windows"

    [[OpenFHE_int128.download]]
    sha256 = "cc9583fefa8f8efe525ab2657a106e3ab92f9669aa3c02feb4f062d2dbd131ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.2.4+0/OpenFHE_int128.v1.2.4.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
